### PR TITLE
switching from MIT to Apache 2

### PR DESCRIPTION
**Pull request by himynamesdave**

### CODE REVIEW

**Review by canic-eiq — DISMISSED** [review]

**Comment by petarc-eiq** [comment]
@himynamesdave Existing extensions already have `The MIT License` in their LICENSE.md files. Should we update those too? //cc @canic-eiq

**Comment by himynamesdave** [comment]
> Existing extensions already have The MIT License in their LICENSE.md files.

@petarc-eiq good spot-- yes need changing to Apache 2.0, and cookie cutter should only show Apache 2.0 also

**Comment by petarc-eiq** [comment]
@himynamesdave I updated the LICENCE files and cookiecutter. I put the whole content of LICENCE.md in cookiecutter template, is that ok or should I leave the shortened version (as it was)?

**Review by canic-eiq — APPROVED** [review]

**Review by canic-eiq — APPROVED** [review]

**Comment by himynamesdave** [comment]
LGTM

**Pull request merged**
